collections:
  cars:
    schema:
      - name: make
        type: string
        required: true
      - name: model
        type: string
        required: true
      - name: year
        type: number
        required: true
      - name: description
        type: text
        required: false
      - name: imageccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        type: string
        required: false
